// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: follow/follow_message.proto

package pb_fl

import (
	user "github.com/msqtt/sevencowcloud-shortvideo-service/api/pb/v1/user"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FollowUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FollowingId int64 `protobuf:"varint,1,opt,name=following_id,json=followingId,proto3" json:"following_id,omitempty"`
	FollowedId  int64 `protobuf:"varint,2,opt,name=followed_id,json=followedId,proto3" json:"followed_id,omitempty"`
}

func (x *FollowUserRequest) Reset() {
	*x = FollowUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_follow_follow_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FollowUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowUserRequest) ProtoMessage() {}

func (x *FollowUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_follow_follow_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowUserRequest.ProtoReflect.Descriptor instead.
func (*FollowUserRequest) Descriptor() ([]byte, []int) {
	return file_follow_follow_message_proto_rawDescGZIP(), []int{0}
}

func (x *FollowUserRequest) GetFollowingId() int64 {
	if x != nil {
		return x.FollowingId
	}
	return 0
}

func (x *FollowUserRequest) GetFollowedId() int64 {
	if x != nil {
		return x.FollowedId
	}
	return 0
}

type FollowUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FollowedAt int64 `protobuf:"varint,1,opt,name=followed_at,json=followedAt,proto3" json:"followed_at,omitempty"`
}

func (x *FollowUserResponse) Reset() {
	*x = FollowUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_follow_follow_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FollowUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowUserResponse) ProtoMessage() {}

func (x *FollowUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_follow_follow_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowUserResponse.ProtoReflect.Descriptor instead.
func (*FollowUserResponse) Descriptor() ([]byte, []int) {
	return file_follow_follow_message_proto_rawDescGZIP(), []int{1}
}

func (x *FollowUserResponse) GetFollowedAt() int64 {
	if x != nil {
		return x.FollowedAt
	}
	return 0
}

type UnFollowUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FollowingId int64 `protobuf:"varint,1,opt,name=following_id,json=followingId,proto3" json:"following_id,omitempty"`
	FollowedId  int64 `protobuf:"varint,2,opt,name=followed_id,json=followedId,proto3" json:"followed_id,omitempty"`
}

func (x *UnFollowUserRequest) Reset() {
	*x = UnFollowUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_follow_follow_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnFollowUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnFollowUserRequest) ProtoMessage() {}

func (x *UnFollowUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_follow_follow_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnFollowUserRequest.ProtoReflect.Descriptor instead.
func (*UnFollowUserRequest) Descriptor() ([]byte, []int) {
	return file_follow_follow_message_proto_rawDescGZIP(), []int{2}
}

func (x *UnFollowUserRequest) GetFollowingId() int64 {
	if x != nil {
		return x.FollowingId
	}
	return 0
}

func (x *UnFollowUserRequest) GetFollowedId() int64 {
	if x != nil {
		return x.FollowedId
	}
	return 0
}

type UnFollowUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Now int64 `protobuf:"varint,1,opt,name=now,proto3" json:"now,omitempty"`
}

func (x *UnFollowUserResponse) Reset() {
	*x = UnFollowUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_follow_follow_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnFollowUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnFollowUserResponse) ProtoMessage() {}

func (x *UnFollowUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_follow_follow_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnFollowUserResponse.ProtoReflect.Descriptor instead.
func (*UnFollowUserResponse) Descriptor() ([]byte, []int) {
	return file_follow_follow_message_proto_rawDescGZIP(), []int{3}
}

func (x *UnFollowUserResponse) GetNow() int64 {
	if x != nil {
		return x.Now
	}
	return 0
}

type CheckFollowRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FollowingId int64 `protobuf:"varint,1,opt,name=following_id,json=followingId,proto3" json:"following_id,omitempty"`
	FollowedId  int64 `protobuf:"varint,2,opt,name=followed_id,json=followedId,proto3" json:"followed_id,omitempty"`
}

func (x *CheckFollowRequest) Reset() {
	*x = CheckFollowRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_follow_follow_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckFollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFollowRequest) ProtoMessage() {}

func (x *CheckFollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_follow_follow_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFollowRequest.ProtoReflect.Descriptor instead.
func (*CheckFollowRequest) Descriptor() ([]byte, []int) {
	return file_follow_follow_message_proto_rawDescGZIP(), []int{4}
}

func (x *CheckFollowRequest) GetFollowingId() int64 {
	if x != nil {
		return x.FollowingId
	}
	return 0
}

func (x *CheckFollowRequest) GetFollowedId() int64 {
	if x != nil {
		return x.FollowedId
	}
	return 0
}

type CheckFollowResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsFollowing bool  `protobuf:"varint,1,opt,name=is_following,json=isFollowing,proto3" json:"is_following,omitempty"`
	FollowedAt  int64 `protobuf:"varint,2,opt,name=followed_at,json=followedAt,proto3" json:"followed_at,omitempty"`
}

func (x *CheckFollowResponse) Reset() {
	*x = CheckFollowResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_follow_follow_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckFollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFollowResponse) ProtoMessage() {}

func (x *CheckFollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_follow_follow_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFollowResponse.ProtoReflect.Descriptor instead.
func (*CheckFollowResponse) Descriptor() ([]byte, []int) {
	return file_follow_follow_message_proto_rawDescGZIP(), []int{5}
}

func (x *CheckFollowResponse) GetIsFollowing() bool {
	if x != nil {
		return x.IsFollowing
	}
	return false
}

func (x *CheckFollowResponse) GetFollowedAt() int64 {
	if x != nil {
		return x.FollowedAt
	}
	return 0
}

type FollowingListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *FollowingListRequest) Reset() {
	*x = FollowingListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_follow_follow_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FollowingListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowingListRequest) ProtoMessage() {}

func (x *FollowingListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_follow_follow_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowingListRequest.ProtoReflect.Descriptor instead.
func (*FollowingListRequest) Descriptor() ([]byte, []int) {
	return file_follow_follow_message_proto_rawDescGZIP(), []int{6}
}

func (x *FollowingListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type FollowingListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []*user.UserItem `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *FollowingListResponse) Reset() {
	*x = FollowingListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_follow_follow_message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FollowingListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowingListResponse) ProtoMessage() {}

func (x *FollowingListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_follow_follow_message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowingListResponse.ProtoReflect.Descriptor instead.
func (*FollowingListResponse) Descriptor() ([]byte, []int) {
	return file_follow_follow_message_proto_rawDescGZIP(), []int{7}
}

func (x *FollowingListResponse) GetUsers() []*user.UserItem {
	if x != nil {
		return x.Users
	}
	return nil
}

type FollowedListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *FollowedListRequest) Reset() {
	*x = FollowedListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_follow_follow_message_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FollowedListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowedListRequest) ProtoMessage() {}

func (x *FollowedListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_follow_follow_message_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowedListRequest.ProtoReflect.Descriptor instead.
func (*FollowedListRequest) Descriptor() ([]byte, []int) {
	return file_follow_follow_message_proto_rawDescGZIP(), []int{8}
}

func (x *FollowedListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type FollowedListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []*user.UserItem `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *FollowedListResponse) Reset() {
	*x = FollowedListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_follow_follow_message_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FollowedListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowedListResponse) ProtoMessage() {}

func (x *FollowedListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_follow_follow_message_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowedListResponse.ProtoReflect.Descriptor instead.
func (*FollowedListResponse) Descriptor() ([]byte, []int) {
	return file_follow_follow_message_proto_rawDescGZIP(), []int{9}
}

func (x *FollowedListResponse) GetUsers() []*user.UserItem {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_follow_follow_message_proto protoreflect.FileDescriptor

var file_follow_follow_message_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x2f, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x66,
	0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x2e, 0x76, 0x31, 0x1a, 0x0f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x57, 0x0a, 0x11, 0x46, 0x6f, 0x6c,
	0x6c, 0x6f, 0x77, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21,
	0x0a, 0x0c, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x49,
	0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64,
	0x49, 0x64, 0x22, 0x35, 0x0a, 0x12, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x6f, 0x6c, 0x6c,
	0x6f, 0x77, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x66,
	0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x41, 0x74, 0x22, 0x59, 0x0a, 0x13, 0x55, 0x6e, 0x46,
	0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x21, 0x0a, 0x0c, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e,
	0x67, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77,
	0x65, 0x64, 0x49, 0x64, 0x22, 0x28, 0x0a, 0x14, 0x55, 0x6e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6e, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6e, 0x6f, 0x77, 0x22, 0x58,
	0x0a, 0x12, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e,
	0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x66, 0x6f, 0x6c, 0x6c,
	0x6f, 0x77, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x6f, 0x6c, 0x6c, 0x6f,
	0x77, 0x65, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x66, 0x6f,
	0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x49, 0x64, 0x22, 0x59, 0x0a, 0x13, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x21, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69,
	0x6e, 0x67, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65,
	0x64, 0x41, 0x74, 0x22, 0x2f, 0x0a, 0x14, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x40, 0x0a, 0x15, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e,
	0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a,
	0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x22, 0x2e, 0x0a, 0x13, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77,
	0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3f, 0x0a, 0x14, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77,
	0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27,
	0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x42, 0x4a, 0x5a, 0x48, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x73, 0x71, 0x74, 0x74, 0x2f, 0x73, 0x65, 0x76, 0x65,
	0x6e, 0x63, 0x6f, 0x77, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2d, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x76,
	0x69, 0x64, 0x65, 0x6f, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x70, 0x62, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x3b, 0x70, 0x62,
	0x5f, 0x66, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_follow_follow_message_proto_rawDescOnce sync.Once
	file_follow_follow_message_proto_rawDescData = file_follow_follow_message_proto_rawDesc
)

func file_follow_follow_message_proto_rawDescGZIP() []byte {
	file_follow_follow_message_proto_rawDescOnce.Do(func() {
		file_follow_follow_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_follow_follow_message_proto_rawDescData)
	})
	return file_follow_follow_message_proto_rawDescData
}

var file_follow_follow_message_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_follow_follow_message_proto_goTypes = []interface{}{
	(*FollowUserRequest)(nil),     // 0: follow.v1.FollowUserRequest
	(*FollowUserResponse)(nil),    // 1: follow.v1.FollowUserResponse
	(*UnFollowUserRequest)(nil),   // 2: follow.v1.UnFollowUserRequest
	(*UnFollowUserResponse)(nil),  // 3: follow.v1.UnFollowUserResponse
	(*CheckFollowRequest)(nil),    // 4: follow.v1.CheckFollowRequest
	(*CheckFollowResponse)(nil),   // 5: follow.v1.CheckFollowResponse
	(*FollowingListRequest)(nil),  // 6: follow.v1.FollowingListRequest
	(*FollowingListResponse)(nil), // 7: follow.v1.FollowingListResponse
	(*FollowedListRequest)(nil),   // 8: follow.v1.FollowedListRequest
	(*FollowedListResponse)(nil),  // 9: follow.v1.FollowedListResponse
	(*user.UserItem)(nil),         // 10: user.v1.UserItem
}
var file_follow_follow_message_proto_depIdxs = []int32{
	10, // 0: follow.v1.FollowingListResponse.users:type_name -> user.v1.UserItem
	10, // 1: follow.v1.FollowedListResponse.users:type_name -> user.v1.UserItem
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_follow_follow_message_proto_init() }
func file_follow_follow_message_proto_init() {
	if File_follow_follow_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_follow_follow_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FollowUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_follow_follow_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FollowUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_follow_follow_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnFollowUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_follow_follow_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnFollowUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_follow_follow_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckFollowRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_follow_follow_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckFollowResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_follow_follow_message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FollowingListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_follow_follow_message_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FollowingListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_follow_follow_message_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FollowedListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_follow_follow_message_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FollowedListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_follow_follow_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_follow_follow_message_proto_goTypes,
		DependencyIndexes: file_follow_follow_message_proto_depIdxs,
		MessageInfos:      file_follow_follow_message_proto_msgTypes,
	}.Build()
	File_follow_follow_message_proto = out.File
	file_follow_follow_message_proto_rawDesc = nil
	file_follow_follow_message_proto_goTypes = nil
	file_follow_follow_message_proto_depIdxs = nil
}
