version: '3'
services:
  shortvideo-mysql:
    container_name: shortvideo-mysql-dev
    image: mysql:8.0.34
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: shortvideo
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./my.cnf:/etc/my.cnf
  api:
    build:
      context: ../build/Dockerfile
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      - DB_SOURCE="root:password@tcp(localhost:3306)/shortvideo?charset=utf8&parseTime=true&loc=Local&time_zone=%27Asia%2FShanghai%27"
      - GRPC_ADDR="0.0.0.0:9090"
      - HTTP_ADDR="0.0.0.0:8080"
      - TOKEN_SYMMETRIC_KEY=
      - ACCESS_DURATION=5h
      - REFLESH_DURATION=
      - SMTP_HOST=smtp.qq.com
      - SMTP_PORT=587
      - SMTP_ADDR=
      - SMTP_SECRET=
      - ACTIVATE_TIMES=5
      - KODO_LINK="http://s3ao0dx1e.hn-bkt.clouddn.com"
      - KODO_HTTPS=0
      - KODO_CDN=0
      - KODO_BUCKET=
      - QINIU_AK=
      - QINIU_SK=
      - IMAGE_LIMIT=2
      - VIDEO_LIMIT=2048
    depends_on:
      postgres:
        condition: service_healthy
