// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: post/post_message.proto

package pb_pst

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadPostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string  `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description string  `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	UserId      int64   `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TagIds      []int32 `protobuf:"varint,4,rep,packed,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`
	VideoId     int64   `protobuf:"varint,5,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
}

func (x *UploadPostRequest) Reset() {
	*x = UploadPostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_post_post_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPostRequest) ProtoMessage() {}

func (x *UploadPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_post_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPostRequest.ProtoReflect.Descriptor instead.
func (*UploadPostRequest) Descriptor() ([]byte, []int) {
	return file_post_post_message_proto_rawDescGZIP(), []int{0}
}

func (x *UploadPostRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UploadPostRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UploadPostRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UploadPostRequest) GetTagIds() []int32 {
	if x != nil {
		return x.TagIds
	}
	return nil
}

func (x *UploadPostRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type UploadPostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostItem *PostItem `protobuf:"bytes,1,opt,name=post_item,json=postItem,proto3" json:"post_item,omitempty"`
}

func (x *UploadPostResponse) Reset() {
	*x = UploadPostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_post_post_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPostResponse) ProtoMessage() {}

func (x *UploadPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_post_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPostResponse.ProtoReflect.Descriptor instead.
func (*UploadPostResponse) Descriptor() ([]byte, []int) {
	return file_post_post_message_proto_rawDescGZIP(), []int{1}
}

func (x *UploadPostResponse) GetPostItem() *PostItem {
	if x != nil {
		return x.PostItem
	}
	return nil
}

var File_post_post_message_proto protoreflect.FileDescriptor

var file_post_post_message_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x6f, 0x73, 0x74, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x6f, 0x73, 0x74, 0x2e,
	0x76, 0x31, 0x1a, 0x0f, 0x70, 0x6f, 0x73, 0x74, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x98, 0x01, 0x0a, 0x11, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x6f,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61,
	0x67, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x74, 0x61, 0x67,
	0x49, 0x64, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x69, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x22, 0x44,
	0x0a, 0x12, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x09, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x74, 0x65,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x74,
	0x49, 0x74, 0x65, 0x6d, 0x42, 0x49, 0x5a, 0x47, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6d, 0x73, 0x71, 0x74, 0x74, 0x2f, 0x73, 0x65, 0x76, 0x65, 0x6e, 0x63, 0x6f,
	0x77, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2d, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x76, 0x69, 0x64, 0x65,
	0x6f, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62,
	0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x3b, 0x70, 0x62, 0x5f, 0x70, 0x73, 0x74, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_post_post_message_proto_rawDescOnce sync.Once
	file_post_post_message_proto_rawDescData = file_post_post_message_proto_rawDesc
)

func file_post_post_message_proto_rawDescGZIP() []byte {
	file_post_post_message_proto_rawDescOnce.Do(func() {
		file_post_post_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_post_post_message_proto_rawDescData)
	})
	return file_post_post_message_proto_rawDescData
}

var file_post_post_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_post_post_message_proto_goTypes = []interface{}{
	(*UploadPostRequest)(nil),  // 0: post.v1.UploadPostRequest
	(*UploadPostResponse)(nil), // 1: post.v1.UploadPostResponse
	(*PostItem)(nil),           // 2: post.v1.PostItem
}
var file_post_post_message_proto_depIdxs = []int32{
	2, // 0: post.v1.UploadPostResponse.post_item:type_name -> post.v1.PostItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_post_post_message_proto_init() }
func file_post_post_message_proto_init() {
	if File_post_post_message_proto != nil {
		return
	}
	file_post_post_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_post_post_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadPostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_post_post_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadPostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_post_post_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_post_post_message_proto_goTypes,
		DependencyIndexes: file_post_post_message_proto_depIdxs,
		MessageInfos:      file_post_post_message_proto_msgTypes,
	}.Build()
	File_post_post_message_proto = out.File
	file_post_post_message_proto_rawDesc = nil
	file_post_post_message_proto_goTypes = nil
	file_post_post_message_proto_depIdxs = nil
}
