// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: profile/update_message.proto

package pb_prf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateProfileRequest_Gender int32

const (
	UpdateProfileRequest_unknown UpdateProfileRequest_Gender = 0
	UpdateProfileRequest_male    UpdateProfileRequest_Gender = 1
	UpdateProfileRequest_female  UpdateProfileRequest_Gender = 2
)

// Enum value maps for UpdateProfileRequest_Gender.
var (
	UpdateProfileRequest_Gender_name = map[int32]string{
		0: "unknown",
		1: "male",
		2: "female",
	}
	UpdateProfileRequest_Gender_value = map[string]int32{
		"unknown": 0,
		"male":    1,
		"female":  2,
	}
)

func (x UpdateProfileRequest_Gender) Enum() *UpdateProfileRequest_Gender {
	p := new(UpdateProfileRequest_Gender)
	*p = x
	return p
}

func (x UpdateProfileRequest_Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateProfileRequest_Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_profile_update_message_proto_enumTypes[0].Descriptor()
}

func (UpdateProfileRequest_Gender) Type() protoreflect.EnumType {
	return &file_profile_update_message_proto_enumTypes[0]
}

func (x UpdateProfileRequest_Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateProfileRequest_Gender.Descriptor instead.
func (UpdateProfileRequest_Gender) EnumDescriptor() ([]byte, []int) {
	return file_profile_update_message_proto_rawDescGZIP(), []int{0, 0}
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       int64                       `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RealName     string                      `protobuf:"bytes,2,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	Mood         string                      `protobuf:"bytes,3,opt,name=mood,proto3" json:"mood,omitempty"`
	Gender       UpdateProfileRequest_Gender `protobuf:"varint,4,opt,name=gender,proto3,enum=profile.v1.UpdateProfileRequest_Gender" json:"gender,omitempty"`
	BirthDate    int64                       `protobuf:"varint,5,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	Introduction string                      `protobuf:"bytes,6,opt,name=introduction,proto3" json:"introduction,omitempty"`
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profile_update_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_update_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_profile_update_message_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateProfileRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateProfileRequest) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *UpdateProfileRequest) GetMood() string {
	if x != nil {
		return x.Mood
	}
	return ""
}

func (x *UpdateProfileRequest) GetGender() UpdateProfileRequest_Gender {
	if x != nil {
		return x.Gender
	}
	return UpdateProfileRequest_unknown
}

func (x *UpdateProfileRequest) GetBirthDate() int64 {
	if x != nil {
		return x.BirthDate
	}
	return 0
}

func (x *UpdateProfileRequest) GetIntroduction() string {
	if x != nil {
		return x.Introduction
	}
	return ""
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Profile *Profile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profile_update_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_update_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_profile_update_message_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateProfileResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

var File_profile_update_message_proto protoreflect.FileDescriptor

var file_profile_update_message_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x15, 0x70, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x91, 0x02, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x61, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x6f, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6d, 0x6f, 0x6f, 0x64, 0x12, 0x3f, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x06, 0x67,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x69, 0x72, 0x74, 0x68, 0x5f, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x62, 0x69, 0x72, 0x74, 0x68,
	0x44, 0x61, 0x74, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x6e, 0x74, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2b, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x12, 0x0b, 0x0a, 0x07, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x04, 0x6d, 0x61, 0x6c, 0x65, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x66, 0x65, 0x6d,
	0x61, 0x6c, 0x65, 0x10, 0x02, 0x22, 0x46, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d,
	0x0a, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x42, 0x4c, 0x5a,
	0x4a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x73, 0x71, 0x74,
	0x74, 0x2f, 0x73, 0x65, 0x76, 0x65, 0x6e, 0x63, 0x6f, 0x77, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2d,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x3b, 0x70, 0x62, 0x5f, 0x70, 0x72, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_profile_update_message_proto_rawDescOnce sync.Once
	file_profile_update_message_proto_rawDescData = file_profile_update_message_proto_rawDesc
)

func file_profile_update_message_proto_rawDescGZIP() []byte {
	file_profile_update_message_proto_rawDescOnce.Do(func() {
		file_profile_update_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_profile_update_message_proto_rawDescData)
	})
	return file_profile_update_message_proto_rawDescData
}

var file_profile_update_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_profile_update_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_profile_update_message_proto_goTypes = []interface{}{
	(UpdateProfileRequest_Gender)(0), // 0: profile.v1.UpdateProfileRequest.Gender
	(*UpdateProfileRequest)(nil),     // 1: profile.v1.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),    // 2: profile.v1.UpdateProfileResponse
	(*Profile)(nil),                  // 3: profile.v1.Profile
}
var file_profile_update_message_proto_depIdxs = []int32{
	0, // 0: profile.v1.UpdateProfileRequest.gender:type_name -> profile.v1.UpdateProfileRequest.Gender
	3, // 1: profile.v1.UpdateProfileResponse.profile:type_name -> profile.v1.Profile
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_profile_update_message_proto_init() }
func file_profile_update_message_proto_init() {
	if File_profile_update_message_proto != nil {
		return
	}
	file_profile_profile_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_profile_update_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateProfileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profile_update_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateProfileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_profile_update_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_profile_update_message_proto_goTypes,
		DependencyIndexes: file_profile_update_message_proto_depIdxs,
		EnumInfos:         file_profile_update_message_proto_enumTypes,
		MessageInfos:      file_profile_update_message_proto_msgTypes,
	}.Build()
	File_profile_update_message_proto = out.File
	file_profile_update_message_proto_rawDesc = nil
	file_profile_update_message_proto_goTypes = nil
	file_profile_update_message_proto_depIdxs = nil
}
