version: 2
sql:
  - engine: mysql
    queries: ../internal/repo/query/
    schema: ../internal/db/migration/
    gen:
      go:
        package: db
        out: ../internal/repo/sqlc/
        emit_json_tags: true
        emit_empty_slices: true
        emit_interface: true
