// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0
// source: profile.sql

package db

import (
	"context"
	"database/sql"
)

const addProfile = `-- name: AddProfile :execresult
INSERT INTO profiles (
	real_name, mood, gender, birth_date, introduction, avatar_link
) VALUES ( ?, ?, ?, ?, ?, ?)
`

type AddProfileParams struct {
	RealName     sql.NullString     `json:"real_name"`
	Mood         sql.NullString     `json:"mood"`
	Gender       NullProfilesGender `json:"gender"`
	BirthDate    sql.NullTime       `json:"birth_date"`
	Introduction sql.NullString     `json:"introduction"`
	AvatarLink   sql.NullString     `json:"avatar_link"`
}

func (q *Queries) AddProfile(ctx context.Context, arg AddProfileParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addProfile,
		arg.RealName,
		arg.Mood,
		arg.Gender,
		arg.BirthDate,
		arg.Introduction,
		arg.AvatarLink,
	)
}

const deleteProfile = `-- name: DeleteProfile :exec
DELETE FROM profiles
	WHERE id = ?
`

func (q *Queries) DeleteProfile(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProfile, id)
	return err
}

const getProfileByID = `-- name: GetProfileByID :one
SELECT id, real_name, mood, gender, birth_date, introduction, avatar_link, updated_at FROM profiles
WHERE id = ?
`

func (q *Queries) GetProfileByID(ctx context.Context, id int64) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfileByID, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.RealName,
		&i.Mood,
		&i.Gender,
		&i.BirthDate,
		&i.Introduction,
		&i.AvatarLink,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAvatar = `-- name: UpdateAvatar :exec
UPDATE profiles
	SET avatar_link = ?
	WHERE id = ?
`

type UpdateAvatarParams struct {
	AvatarLink sql.NullString `json:"avatar_link"`
	ID         int64          `json:"id"`
}

func (q *Queries) UpdateAvatar(ctx context.Context, arg UpdateAvatarParams) error {
	_, err := q.db.ExecContext(ctx, updateAvatar, arg.AvatarLink, arg.ID)
	return err
}

const updateProfile = `-- name: UpdateProfile :exec
UPDATE profiles
	SET real_name = ?,
			mood = ?,
			gender = ?,
			birth_date = ?,
			introduction = ?,
			updated_at = now()
	WHERE id = ?
`

type UpdateProfileParams struct {
	RealName     sql.NullString     `json:"real_name"`
	Mood         sql.NullString     `json:"mood"`
	Gender       NullProfilesGender `json:"gender"`
	BirthDate    sql.NullTime       `json:"birth_date"`
	Introduction sql.NullString     `json:"introduction"`
	ID           int64              `json:"id"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateProfile,
		arg.RealName,
		arg.Mood,
		arg.Gender,
		arg.BirthDate,
		arg.Introduction,
		arg.ID,
	)
	return err
}
