// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: user/captcha_message.proto

package pb_usr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendCaptchaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *SendCaptchaRequest) Reset() {
	*x = SendCaptchaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_captcha_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendCaptchaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCaptchaRequest) ProtoMessage() {}

func (x *SendCaptchaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_captcha_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCaptchaRequest.ProtoReflect.Descriptor instead.
func (*SendCaptchaRequest) Descriptor() ([]byte, []int) {
	return file_user_captcha_message_proto_rawDescGZIP(), []int{0}
}

func (x *SendCaptchaRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type SendCaptchaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TodayLeftTimes int32 `protobuf:"varint,1,opt,name=today_left_times,json=todayLeftTimes,proto3" json:"today_left_times,omitempty"`
}

func (x *SendCaptchaResponse) Reset() {
	*x = SendCaptchaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_captcha_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendCaptchaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCaptchaResponse) ProtoMessage() {}

func (x *SendCaptchaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_captcha_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCaptchaResponse.ProtoReflect.Descriptor instead.
func (*SendCaptchaResponse) Descriptor() ([]byte, []int) {
	return file_user_captcha_message_proto_rawDescGZIP(), []int{1}
}

func (x *SendCaptchaResponse) GetTodayLeftTimes() int32 {
	if x != nil {
		return x.TodayLeftTimes
	}
	return 0
}

var File_user_captcha_message_proto protoreflect.FileDescriptor

var file_user_captcha_message_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x22, 0x2a, 0x0a, 0x12, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x61, 0x70,
	0x74, 0x63, 0x68, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x22, 0x3f, 0x0a, 0x13, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x74, 0x6f, 0x64, 0x61,
	0x79, 0x5f, 0x6c, 0x65, 0x66, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0e, 0x74, 0x6f, 0x64, 0x61, 0x79, 0x4c, 0x65, 0x66, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x42, 0x49, 0x5a, 0x47, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6d, 0x73, 0x71, 0x74, 0x74, 0x2f, 0x73, 0x65, 0x76, 0x65, 0x6e, 0x63, 0x6f, 0x77, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x2d, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x2d,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0x2f, 0x76,
	0x31, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x3b, 0x70, 0x62, 0x5f, 0x75, 0x73, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_captcha_message_proto_rawDescOnce sync.Once
	file_user_captcha_message_proto_rawDescData = file_user_captcha_message_proto_rawDesc
)

func file_user_captcha_message_proto_rawDescGZIP() []byte {
	file_user_captcha_message_proto_rawDescOnce.Do(func() {
		file_user_captcha_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_captcha_message_proto_rawDescData)
	})
	return file_user_captcha_message_proto_rawDescData
}

var file_user_captcha_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_user_captcha_message_proto_goTypes = []interface{}{
	(*SendCaptchaRequest)(nil),  // 0: user.v1.SendCaptchaRequest
	(*SendCaptchaResponse)(nil), // 1: user.v1.SendCaptchaResponse
}
var file_user_captcha_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_captcha_message_proto_init() }
func file_user_captcha_message_proto_init() {
	if File_user_captcha_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_captcha_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendCaptchaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_captcha_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendCaptchaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_captcha_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_captcha_message_proto_goTypes,
		DependencyIndexes: file_user_captcha_message_proto_depIdxs,
		MessageInfos:      file_user_captcha_message_proto_msgTypes,
	}.Build()
	File_user_captcha_message_proto = out.File
	file_user_captcha_message_proto_rawDesc = nil
	file_user_captcha_message_proto_goTypes = nil
	file_user_captcha_message_proto_depIdxs = nil
}
